services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app_network

  backend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

